name: Telegram News Bot

on:
  schedule:
    - cron: '0 * * * *'   # 매 시 정각 (UTC 기준)
  workflow_dispatch:       # 수동 실행도 가능

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run:  pip install python-telegram-bot==20.3 requests python-dotenv beautifulsoup4 newspaper3k lxml[html_clean]

      - name: Run bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          GOOGLE_CSE_ID: ${{ secrets.GOOGLE_CSE_ID }}
        run: python newsbot.py
        
      - name: Save sent_articles cache
        uses: actions/cache@v3
        with:
          path: sent_articles.json
          key: sent-articles-cache-${{ github.run_id }}
          restore-keys: sent-articles-cache

      - name: Save sent_articles backup
        uses: actions/upload-artifact@v3
        with:
          name: sent_articles
          path: sent_articles.json
