name: Telegram News Bot

on:
  schedule:
    - cron: '0 * * * *'   # 매 시 정각 (UTC 기준)
  workflow_dispatch:       # 수동 실행도 가능

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run:  pip install python-telegram-bot==20.3 requests python-dotenv beautifulsoup4

      - name: Run bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          GOOGLE_CSE_ID: ${{ secrets.GOOGLE_CSE_ID }}
        run: python newsbot.py
